name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}
      current-person:
        description: 'The person greeted.'
        value: ${{ jobs.reusable-job.outputs.current-person }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: |
          echo $GITHUB_OUTPUT
          echo "timevar=$(date)" >> $GITHUB_OUTPUT
          echo "personvar=${{ inputs.who-to-greet }}" >> $GITHUB_OUTPUT
    outputs:
      current-time: ${{ steps.time.outputs.timevar }}
      current-person: ${{ steps.time.outputs.personvar }}
